// @ts-check
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import react from '@astrojs/react';
import vercel from '@astrojs/vercel';

// https://astro.build/config
export default defineConfig({
  site: 'https://www.casinous.com',
  build: {
    inlineStylesheets: 'always',
  },
  output: 'static',
  adapter: vercel(),
  vite: {
    plugins: [tailwindcss()]
  },
  integrations: [react()],

  trailingSlash: 'always',
  image: {
    domains: [
      'www.casinous.com', 
      'casinous.com', 
      'wordpress-1417050-6335380.cloudwaysapps.com', 
      'www.wordpress-1417050-6335380.cloudwaysapps.com',
      'wordpress-1621926-6409582.cloudwaysapps.com',
      'secure.gravatar.com',
      'ui-avatars.com'
    ]
  },

  redirects: {
    '/to': { status: 302, destination: '/finwiz-admin.php' },
    '/finwiz-admin': { status: 302, destination: '/finwiz-admin.php' },
    '/play/clubworld-hp': 'http://tracking.affiliateedge.eu/default.aspx?AffUserID=10973&casinoID=181',
    '/play/lucky-red-hp': 'https://trace.affiliateedge.com/visit/?bta=36654&brand=lrc',
    '/play/aladdins-gold-casino': 'https://trace.affiliateedge.com/visit/?bta=36654&brand=agc',
    '/play/allstar-slots-casino': 'https://trace.affiliateedge.com/visit/?bta=36654&nci=5425',
    '/land-based-casinos': '/united-states',
    '/play/Intertops-casino-hpt': 'http://affiliate.intertops.eu/processing/clickthrgh.asp?btag=a_12471b_1470',
    '/play/jackpot-capital-casino-hpt': 'https://downloads.jackpotcapital.eu/affiliate/remote/aiddownload.asp?casinoID=272&gAID=50320&subGid=0&bannerID=14532',
    '/play/slotastic-casino-hpt': 'http://downloads.slotastic.com/affiliate/remote/aiddownload.asp?casinoID=381&gAID=50323&subGid=0&bannerID=13467',
    '/play/grande-vegas-casino-hpt': 'https://link.totalaffiliates.com/c/622743',
    '/play/springbok-casino-hpt': 'https://wordpress-1621926-6409582.cloudwaysapps.com/',
    '/play/thunder-bolt-hpt': 'https://wordpress-1621926-6409582.cloudwaysapps.com/',
    '/play/yebo-casino-hpt': 'https://wordpress-1621926-6409582.cloudwaysapps.com/',
    '/online-gambling-laws/capture-6': '/online-gambling-laws/',
    '/2016/09/26/hello-world-2': 'https://wordpress-1621926-6409582.cloudwaysapps.com/',
    '/online-roulette-2': '/online-roulette/',
    '/casino-games/free-casino-games/shutterstock_439390204': '/casino-games/free-casino-games/',
    '/play/coolcat-hpt': 'https://www.coolcatlinks.com/click/7/3936/12600/1',
    '/play/planet7-hpt': 'https://www.p7promolinks.com/click/2/10455/21091/1',
    '/play/slots-of-vegas-hpt': 'http://www.slotsofvegaslinks.com/click/15/3885/12600/1',
    '/play/royal-ace-hpt': 'https://www.royalacelinks.com/click/3/10338/21091/1',
    '/play/raging-bull-hpt': 'https://www.ragingbullpromos.com/click/27/493/4975/1',
    '/play/lasvegas-casino-us': 'https://link.totalaffiliates.com/c/713773',
    '/play/jackpot-wheel': 'http://promo.jackpotwheel.com/100-free/?cid=2B413N2',
    '/play/sunpalace-us': 'https://link.totalaffiliates.com/c/646899',
    '/uncategorized/page/3': '/blog/',
    '/author/abi': '/',
    '/play/lasvegas-casino-logo-us': 'https://link.totalaffiliates.com/c/713773',
    '/play/vegascasino-us': 'https://link.totalaffiliates.com/c/622743',
    '/play/oldhavana-casino': 'https://oldhavanacasino.eu/56225/',
    '/tables': '/',
    '/play/drake': 'https://promos.drakecasino.eu/welcome2drake/?refer=17592',
    '/play/gossip-slots': 'https://www.gossipslots.eu?refer=17593',
    '/play/liberty-slots': 'https://link.slotsvendor.eu/c/2072',
    '/play/lincoln-casino': 'https://link.slotsvendor.eu/c/2065',
    '/play/slots-plus-us': 'https://link.totalaffiliates.com/c/725900',
    '/online-casino-reviews': '/casino-reviews/',
    '/planet-7-casino-review-us-players': '/planet-7-casino-review/',
    '/play/casino-max': 'https://record.legendaffiliates.com/_kdwiDL1GYegdHrf4TDP9mWNd7ZgqdRLk/1/',
    '/hard-rock-atlantic-city-set-open-without-sportsbook': '/',
    '/us-sports-betting-market-could-become-largest-in-the-world': '/sports-betting/',
    '/play/lucky-red': 'https://trace.affiliateedge.com/visit/?bta=36654&brand=lrc',
    '/play/club-world': 'https://trace.affiliateedge.com/visit/?bta=36654&nci=5347',
    '/play/high-noon': 'https://trace.affiliateedge.com/visit/?bta=36654&nci=5399',
    '/play/manhattan-slots': 'https://trace.affiliateedge.com/visit/?bta=36654&nci=5440',
    '/how-to-play-online-blackjack-2': '/how-to-play-blackjack/',
    '/united-states': '/',
    '/united-states$': '/',
    '/banking$': '/casino-banking/',
    '/banking': '/casino-banking/',
    '/ecash_merch.asp$': '/',
    '/wp-content/uploads/2017/10/las-vegas-usa.pn$': '/',
    '/wp-content/uploads/2017/10/las-vegas-usa$': '/',
    '/download.asp$': '/',
    '/play/silver-oaks': 'https://www.silveroaklinks.com/click/1/10439/21091/1',
    '/play/bovegas-casino': 'https://go.affiliatesleague.com/visit/?bta=36814&nci=29611&campaign=68141',
    '/play/jumba-bet': 'https://www.jumbabet.com?cid=26WD860&mid=2228PJ88',
    '/uncategorized': '/',
    '/homepage_table/vegas-casino-online': '/',
    '/english/contact.asp$': '/',
    '/play/cafe-casino-us': 'https://record.revenuenetwork.com/_7Z5ye18KQ6cWTzEdeSzpw2Nd7ZgqdRLk/1/',
    '/play/cafe-casino.lv': 'https://record.revenuenetwork.com/_7Z5ye18KQ6cWTzEdeSzpw2Nd7ZgqdRLk/1/',
    '/play/ignition-casino': 'https://record.revenuenetwork.com/_7Z5ye18KQ6erQPzF2DiSImNd7ZgqdRLk/1/',
    '/play/slotslv': 'https://record.revenuenetwork.com/_7Z5ye18KQ6dX-OnlyRvJXmNd7ZgqdRLk/1/',
    '/play/bovada': 'https://record.revenuenetwork.com/_7Z5ye18KQ6eZnvZqY1UR2mNd7ZgqdRLk/1/',
    '/play/golden-lion': 'https://go.affiliatesleague.com/visit/?bta=36814&nci=29607&campaign=68141',
    '/play/supernova': 'https://go.affiliatesleague.com/visit/?bta=36814&nci=29606&campaign=68141',
    '/play/eclipse': 'https://go.affiliatesleague.com/visit/?bta=36814&nci=29609&campaign=68141',
    '/play/exclusive-casino': 'https://go.affiliatesleague.com/visit/?bta=36814&nci=29614&campaign=68141',
    '/play/freespin': 'https://go.affiliatesleague.com/visit/?bta=36814&nci=29613&campaign=68141',
    '/play/twoup-casino': 'https://go.affiliatesleague.com/visit/?bta=36814&nci=29615&campaign=68141',
    '/play/irish-luck-casino': 'https://go.affiliatesleague.com/visit/?bta=36814&nci=29617&campaign=68141',
    '/play/domgame-casino': 'https://go.affiliatesleague.com/visit/?bta=36814&nci=29616&campaign=68141',
    '/play/crypto-reels-casino': 'https://record.rivierarewards.com/_QaB3lX_K2H1fWQTENI37dGNd7ZgqdRLk/10/',
    '/play/reelsofjoy': 'https://record.rivierarewards.com/_QaB3lX_K2H1fWQTENI37dGNd7ZgqdRLk/10/',
    '/play/slotsofvegas-casino': 'https://www.slotsofvegaslinks.com/click/15/4204/12600/1',
    '/play/cherryjackpot': 'https://record.legendaffiliates.com/_kdwiDL1GYegOMRDMpvVHzmNd7ZgqdRLk/1/',
    '/play/roaring21': 'https://record.legendaffiliates.com/_kdwiDL1GYei22a5QkwDt8GNd7ZgqdRLk/1/',
    '/play/red-dog-casino': 'https://record.toponepartners.com/_ScVkjN-Rwalr_ND_YXyCpWNd7ZgqdRLk/1/',
    '/play/buzz-luck-casino': 'https://trace.affiliateedge.com/visit/?bta=36654&brand=bzl',
    '/play/wild-vegas-casino': 'https://www.wildvegaslinks.com/click/11/3908/12600/1',
    '/play/prism-casino': 'https://www.prismlinks.com/click/14/1255/12600/1',
    '/play/ruby-slots-casino': 'https://www.rubyslotslinks.com/click/13/4024/12600/1',
    '/play/palace-of-chance-casino': 'https://www.palaceofchancelinks.com/click/10/3766/12600/1',
    '/play/dreams-casino': 'https://www.dreamslinks.com/click/6/4025/12600/1',
    '/play/high-country': 'http://downloads.highcountrycasino.com/affiliate/remote/aiddownload.asp?casinoID=938&gAID=56225&subGid=0&bannerID=0',
    '/play/club-player-casino': 'https://www.clubplayerlinks.com/click/9/4026/12600/1',
    '/online-casino': '/',
    '/online-casino-benefits': '/',
    '/play/aladdins-gold-hp': 'https://trace.affiliateedge.com/visit/?bta=36654&brand=agc',
    '/play/bingo-fest': 'https://record.vistagamingaffiliates.net/_o3IymBZX7XSYNevImT-MDGNd7ZgqdRLk/1/',
    '/play/bingo-spirit': 'https://record.vistagamingaffiliates.net/_o3IymBZX7XRD3TEmsPWI0WNd7ZgqdRLk/1/',
    '/play/cyber-spins': 'https://record.vistagamingaffiliates.net/_o3IymBZX7XTFHJllK_NOEWNd7ZgqdRLk/1/',
    '/play/aussie-play': 'https://record.toponepartners.com/_ScVkjN-RwanraMYPxMYS8mNd7ZgqdRLk/1/',
    '/play/slots-empire': 'https://record.toponepartners.com/_ScVkjN-RwakOMRDMpvVHzmNd7ZgqdRLk/1/',
    '/play/el-royale': 'https://record.toponepartners.com/_ScVkjN-RwalypJyhO2g1tWNd7ZgqdRLk/1/',
    '/play/cyberspins': 'https://record.vistagamingaffiliates.net/_o3IymBZX7XTFHJllK_NOEWNd7ZgqdRLk/1/',
    '/blackjack': '/online-blackjack/',
    '/roulette': '/online-roulette/',
    '/jumba-bet-casino-review': '/casino-reviews/',
    '/play/sports-casino': 'http://get.sportsandcasino.com/get/a/4421888',
    '/betsoft-gaming': '/software-providers/betsoft/',
    '/rival-software': '/software-providers/rival/',
    '/play/hippo-casino': 'http://affiliates.luckyhippocasino.eu/affiliate/remote/aiddownload.asp?casinoID=949&gAID=56225&subGid=0&bannerID=22550',
    '/play/crest-casino': 'https://record.vistagamingaffiliates.net/_w1a6M1cdlG5H0ro-ki_vp2Nd7ZgqdRLk/1/',
    '/which-online-casino-has-the-fastest-withdrawal-time': '/which-casino-has-the-fastest-withdrawal-time/',
    '/play/highway-casino': 'https://record.jackpot-partners.com/_kgQEZl9Y54L6PBA04iUMN2Nd7ZgqdRLk/2/?pg=0',
    '/play/busr-casino': 'https://record.webpartners.co/_NtB1QSVhmWqWOx4zHaEN5WNd7ZgqdRLk/9/',
    '/play/mybookie-casino': 'https://record.webpartners.co/_NtB1QSVhmWqVAv0U_Fv2nWNd7ZgqdRLk/9/',
    '/play/myb-casino': 'https://record.webpartners.co/_NtB1QSVhmWqPb6HlHYETZ2Nd7ZgqdRLk/9/',
    '/play/xbet-casino': 'https://record.webpartners.co/_NtB1QSVhmWo8TL4kmJ7MEGNd7ZgqdRLk/9/',
    '/play/betonline-casino': 'https://record.commissionkings.ag/_MK29geVmL_nfkb3gg_bGdGNd7ZgqdRLk/9/',
    '/play/sports-betting': 'https://record.commissionkings.ag/_MK29geVmL_nT2Fu8bIPGIGNd7ZgqdRLk/9/',
    '/play/super-slots-casino': 'https://record.commissionkings.ag/_MK29geVmL_kgYyObb-IxMmNd7ZgqdRLk/9/',
    '/play/rich-palms-casino': 'https://record.superiorshare.com/_TusvNThj_BHGymNLMU_AeGNd7ZgqdRLk/10/',
    '/play/lucky-tiger-casino': 'https://record.superiorshare.com/_TusvNThj_BFURo-rjP9CI2Nd7ZgqdRLk/10/',
    '/play/tiger-gaming': 'https://record.commissionkings.ag/_MK29geVmL_myRtIjHPVZtGNd7ZgqdRLk/9/',
    '/play/wild-online-casino': 'https://record.wildcasinoaffiliate.ag/_MK29geVmL_n6PBA04iUMN2Nd7ZgqdRLk/9/',
    '/play/comic-play-casino': 'https://record.jackpot-partners.com/_kgQEZl9Y54LlE-K0mpYMyWNd7ZgqdRLk/2/',
    '/play/true-fortune-casino': 'https://go.truebetaffiliates.com/visit/?bta=35962&nci=5547&utm_campaign=CASINO%20US',
    '/play/shazam-casino': 'https://record.superiorshare.com/_TusvNThj_BEZV93hC2dJ_GNd7ZgqdRLk/10/?pg=2',
    '/play/extreme-casino': 'https://record.xmarkaffiliates.com/_xfzl4TRUwAjUOsjNOfgKeWNd7ZgqdRLk/3/',
    '/play/brango-casino': 'https://record.xmarkaffiliates.com/_xfzl4TRUwAiVAv0U_Fv2nWNd7ZgqdRLk/3/',
    '/play/yabby-casino': 'https://record.xmarkaffiliates.com/_xfzl4TRUwAiUcyqUL4Bc9GNd7ZgqdRLk/3/',
    '/play/grand-rush': 'https://record.graphiteaffiliates.com/_YpoSR4bcDFu77L7zifyVX2Nd7ZgqdRLk/1/',
    '/play/juicy-vegas': 'https://record.graphiteaffiliates.com/_YpoSR4bcDFsX6witB42GqWNd7ZgqdRLk/1/',
    '/play/betus-casino': 'https://record.revmasters.com/_9E0BOAU0a4TUOsjNOfgKeWNd7ZgqdRLk/2/',
    '/play/las-atlantis': 'https://record.toponepartners.com/_ScVkjN-RwanlRqYtzC2ttWNd7ZgqdRLk/1/',
    '/play/cherry-gold': 'https://go.affiliatesleague.com/visit/?bta=36814&nci=29612&campaign=68141',
    '/play-now/prive-city-casino': 'https://www.privecity.com/en',
    '/play/4-wilds-casino': 'https://www.4wilds.com/en',
    '/play/dazzle-casino': 'https://www.dazzlefortune.com/home',
    '/play/spinfinity': 'https://record.legendaffiliates.com/_kdwiDL1GYejGs5YK48Vb6WNd7ZgqdRLk/1/',
    '/play/grande-vegas': 'https://link.affiliatecapital.com/c/435364',
    '/play/slotastic-casino': 'https://link.affiliatecapital.com/c/435365',
    '/play/jackpot-capital-casino': 'https://link.affiliatecapital.com/c/435366',
    '/play/slotsroom': 'https://record.legendaffiliates.com/_kdwiDL1GYejYGgllr3Vm5GNd7ZgqdRLk/1/',
    '/play/slotsninja': 'https://record.legendaffiliates.com/_kdwiDL1GYehRZS2G957ZqGNd7ZgqdRLk/1/',
    '/play/limitless-casino': 'https://record.xmarkaffiliates.com/_xfzl4TRUwAihJjIwNC_yVWNd7ZgqdRLk/3/',
    '/play/punt-casino': 'https://www.puntlinks.com/click/41/455/3496/1',
    '/play/crypto-loko': 'https://cryptolokolink.com/click/77/457/3496/1',
    '/play/kings-chance': 'https://www.kingschancelinks.com/click/43/322/1679/1/CasinoUS',
    '/play/winstark': 'https://go.truebetaffiliates.com/visit/?bta=35652&nci=5658&utm_campaign=casinous',
    '/play/kaboom': 'https://go.truebetaffiliates.com/visit/?bta=35652&nci=5635&utm_campaign=casinous',
    '/play/red-cherry': 'https://record.income-network.com/_IxRSoTmCePEOMRDMpvVHzmNd7ZgqdRLk/1/',
    '/play/lady-luck': 'https://record.income-network.com/_IxRSoTmCePH6PBA04iUMN2Nd7ZgqdRLk/1/',
    '/play/triple-seven': 'https://record.income-network.com/_IxRSoTmCePHKto_EPcZApGNd7ZgqdRLk/1/',
    '/play/inetbet': 'https://record.income-network.com/_IxRSoTmCePGVAv0U_Fv2nWNd7ZgqdRLk/1/',
    '/play/kudos-casino': 'https://record.income-network.com/_IxRSoTmCePEWqcfzuvZcQGNd7ZgqdRLk/1/',
    '/play/primaplay-casino': 'https://record.income-network.com/_IxRSoTmCePFhg6WO2I1rgWNd7ZgqdRLk/1/',
    '/play/slot-madness': 'https://www.slotmadnesslinks.com/click/60/10397/21091/1',
    '/play/captain-jack': 'https://www.captainjacklinks.com/click/5/10420/21091/1',
    '/play/slots-of-vegas-ndb': 'https://www.slotsofvegaslinks.com/click/15/4270/12600/1',
    '/play/thunderpick': 'https://go.thunder.partners/visit/?bta=36041&nci=5502',
    '/play/planet7-ndb': 'https://www.planet7links.com/click/2/10189/16519/1',
    '/play/ducky-luck': 'http://get.duckyluck.ag/get/a/5152105',
    '/play/raging-bull-ndb': 'https://www.ragingbulllinks.com/click/27/291/3500/1',
    '/play/ruby-slots-ndb': 'https://www.rubyslotslinks.com/click/13/4041/12600/1',
    '/play/wild-vegas-ndb': 'https://www.wildvegaslinks.com/click/11/4232/12600/1',
    '/play/prism-ndb': 'https://www.prismlinks.com/click/14/4217/12600/1',
    '/play/palace-of-chance-ndb': 'https://www.palaceofchancelinks.com/click/10/4296/12600/1',
    '/play/club-player-ndb': 'https://www.clubplayerlinks.com/click/9/4263/12600/1',
    '/play/cool-cat-ndb': 'https://www.coolcatlinks.com/click/7/4093/12600/1',
    '/play/slot-madness-ndb': 'https://www.slotmadnesslinks.com/click/60/10408/16519/1',
    '/play/royal-ace-ndb': 'https://www.royalacelinks.com/click/3/10126/16519/1',
    '/play/silver-oak-ndb': 'https://www.silveroaklinks.com/click/1/10401/16519/1',
    '/play/dreams-ndb': 'https://www.dreamslinks.com/click/6/4025/12600/1',
    '/play/captain-jack-ndb': 'https://www.captainjacklinks.com/click/5/10353/16519/1',
    '/play/shazam-ndb-chip': 'https://record.superiorshare.com/_TusvNThj_BEz8P_QUY1PbGNd7ZgqdRLk/10/',
    '/play/shazam-ndb-spins': 'https://record.superiorshare.com/_TusvNThj_BEvQEVUcMeklWNd7ZgqdRLk/10/',
    '/play/lucky-hippo-ndb': 'https://affiliates.luckyhippocasino.eu/affiliate/remote/aiddownload.asp?casinoID=949&gAID=56225&subGid=2&bannerID=25855',
    '/play/sun-palace-ndb': 'https://www.sunpalacecasino.eu/Remote/AidDownload.php?casinoID=236&gAID=56225&subGid=2&bannerID=25850',
    '/play/vegas-casino-ndb': 'https://www.vegascasinoonline.eu/Remote/AidDownload.php?casinoID=234&gAID=56225&subGid=2&bannerID=25853',
    '/play/las-vegas-usa-ndb': 'https://www.lasvegasusa.eu/Remote/AidDownload.php?casinoID=235&gAID=56225&subGid=2&bannerID=25849',
    '/play/slots-plus-ndb': 'https://www.slotsplus.eu/Remote/AidDownload.php?casinoID=237&gAID=56225&subGid=2&bannerID=25852',
    '/play/old-havana-ndb': 'https://downloads.oldhavanacasino.eu/affiliate/remote/aiddownload.asp?casinoID=715&gAID=56225&subGid=2&bannerID=25854',
    '/play/vegas-aces': 'https://record.revmasters.com/_vv3E-UDykDRoZiEtOfHDE2Nd7ZgqdRLk/1/',
    '/play/slots-paradise': 'https://record.revmasters.com/_vv3E-UDykDRqMwBAsL0sWWNd7ZgqdRLk/1/',
    '/play/stake': 'http://stake.com/?c=3rJZ8ALy'
  }
});